apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-vue
  labels:
    app: app-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-vue
  template:
    metadata:
      labels:
        app: app-vue
    spec:
      containers:
      - name: app-vue
        image: app
        imagePullPolicy: Never
        resources:
          limits: 
            memory: 2048Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    app: app-vue
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
    nodePort: 30300


