apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: k8s-cloud-sql
      containers:
      - name: backend
        image: asia.gcr.io/total-messenger-391312/node-gcp
        resources:
          limits: 
            memory: 2048Mi
        ports:
        - containerPort: 3000
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:latest
        args:
          - "--structured-logs"
          - "--port=3306"
          - "app-mysql"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: backend
    port: 3000


