apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node-app
        imagePullPolicy: Never
        resources:
          limits: 
            memory: 2048Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: back-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
    nodePort: 30400


